// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OctofitTracker.Data;

#nullable disable

namespace OctofitTracker.Migrations
{
    [DbContext(typeof(OctofitDbContext))]
    [Migration("20260506091049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("OctofitTracker.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("OctofitTracker.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Outdoor or treadmill run",
                            Name = "Running",
                            Points = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bike ride or stationary bike",
                            Name = "Cycling",
                            Points = 8
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lap swimming",
                            Name = "Swimming",
                            Points = 12
                        },
                        new
                        {
                            Id = 4,
                            Description = "Weight or resistance training",
                            Name = "Strength Training",
                            Points = 9
                        },
                        new
                        {
                            Id = 5,
                            Description = "Yoga or stretching session",
                            Name = "Yoga",
                            Points = 5
                        });
                });

            modelBuilder.Entity("OctofitTracker.Models.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutLogs");
                });

            modelBuilder.Entity("OctofitTracker.Models.WorkoutLog", b =>
                {
                    b.HasOne("OctofitTracker.Models.Student", "Student")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OctofitTracker.Models.Workout", "Workout")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("OctofitTracker.Models.Student", b =>
                {
                    b.Navigation("WorkoutLogs");
                });

            modelBuilder.Entity("OctofitTracker.Models.Workout", b =>
                {
                    b.Navigation("WorkoutLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
